INSERT INTO books (code, title, author, copies_total, copies_available)
VALUES
('BK001','Cien años de soledad','Gabriel García Márquez',5,4),
('BK002','Don Quijote de la Mancha','Miguel de Cervantes',4,4),
('BK003','La sombra del viento','Carlos Ruiz Zafón',6,6),
('BK004','1984','George Orwell',5,5),
('BK005','El alquimista','Paulo Coelho',7,6),
('BK006','Crimen y castigo','Fiódor Dostoyevski',3,3),
('BK007','Orgullo y prejuicio','Jane Austen',4,4),
('BK008','El señor de los anillos','J. R. R. Tolkien',10,9),
('BK009','Matar a un ruiseñor','Harper Lee',3,3),
('BK010','El nombre del viento','Patrick Rothfuss',5,5),
('BK011','Los miserables','Victor Hugo',6,6),
('BK012','Rayuela','Julio Cortázar',5,5),
('BK013','Pedro Páramo','Juan Rulfo',4,4),
('BK014','Fahrenheit 451','Ray Bradbury',4,4),
('BK015','Ensayo sobre la ceguera','José Saramago',5,5),
('BK016','Drácula','Bram Stoker',3,3),
('BK017','Frankenstein','Mary Shelley',4,4),
('BK018','El principito','Antoine de Saint-Exupéry',6,6),
('BK019','Las mil y una noches','Anónimo',5,5),
('BK020','La divina comedia','Dante Alighieri',4,4),
('BK021','La Odisea','Homero',4,4),
('BK022','La Ilíada','Homero',4,4),
('BK023','Ulises','James Joyce',3,3),
('BK024','La metamorfosis','Franz Kafka',5,5),
('BK025','El proceso','Franz Kafka',4,4),
('BK026','Los hermanos Karamázov','Fiódor Dostoyevski',4,4),
('BK027','Guerra y paz','León Tolstói',5,5),
('BK028','Ana Karenina','León Tolstói',5,5),
('BK029','Madame Bovary','Gustave Flaubert',3,3),
('BK030','El retrato de Dorian Gray','Oscar Wilde',4,4),
('BK031','La casa de los espíritus','Isabel Allende',5,5),
('BK032','Memorias de Adriano','Marguerite Yourcenar',4,4),
('BK033','La insoportable levedad del ser','Milan Kundera',5,5),
('BK034','El túnel','Ernesto Sabato',3,3),
('BK035','Sobre héroes y tumbas','Ernesto Sabato',3,3),
('BK036','La tregua','Mario Benedetti',4,4),
('BK037','El amor en los tiempos del cólera','Gabriel García Márquez',6,6),
('BK038','Relato de un náufrago','Gabriel García Márquez',3,3),
('BK039','Noticias de un secuestro','Gabriel García Márquez',3,3),
('BK040','Bestiario','Julio Cortázar',3,3),
('BK041','Final del juego','Julio Cortázar',3,3),
('BK042','Al sur de la frontera, al oeste del sol','Haruki Murakami',4,4),
('BK043','Kafka en la orilla','Haruki Murakami',5,5),
('BK044','Tokio Blues (Norwegian Wood)','Haruki Murakami',5,5),
('BK045','El hombre en busca de sentido','Viktor Frankl',4,4),
('BK046','Los pilares de la tierra','Ken Follett',6,6),
('BK047','Un mundo sin fin','Ken Follett',6,6),
('BK048','La catedral del mar','Ildefonso Falcones',5,5),
('BK049','Patria','Fernando Aramburu',5,5),
('BK050','Sapiens: De animales a dioses','Yuval Noah Harari',7,7)
ON CONFLICT (code) DO NOTHING;

-- préstamos de ejemplo
INSERT INTO loans (book_code, user_id, site_id, due_date, renewals_count, status)
VALUES
('BK001','u01','S1', CURRENT_DATE + INTERVAL '14 days', 0, 'active'),
('BK004','u02','S2', CURRENT_DATE + INTERVAL '10 days', 1, 'active'),
('BK008','u03','S1', CURRENT_DATE + INTERVAL '7 days', 0, 'active'),
('BK050','u04','S2', CURRENT_DATE + INTERVAL '20 days', 0, 'active');
